In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv"
pd.read_csv (url)

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

In [3]:
pd.read_csv(url, sep=';')

   Nome,Idade,Notas,Aprovado
0            Ary,20,7.5,True
1              Ana,18,,False
2         Cátia,27,2.5,False
3         Denis,18,5.0,False
4          Beto,21,10.0,True
5            Bruna,23,,False
6           Dara,21,7.0,True
7         Carlos,19,6.0,True
8         Alice,35,5.6,False
9            Vitor,28,,False
10          Daniel,21,,False
11         Igor,24,4.5,False
12     Sthefanie,26,9.5,True
13         Mirla,25,9.0,True
14           Paulo,37,,False
15        Mylena,29,7.0,True
16           Lucas,33,,False
17         Nadia,34,8.0,True

In [5]:
dados_alunos = pd.read_csv(url, sep=";")
dados_alunos

   Nome,Idade,Notas,Aprovado
0            Ary,20,7.5,True
1              Ana,18,,False
2         Cátia,27,2.5,False
3         Denis,18,5.0,False
4          Beto,21,10.0,True
5            Bruna,23,,False
6           Dara,21,7.0,True
7         Carlos,19,6.0,True
8         Alice,35,5.6,False
9            Vitor,28,,False
10          Daniel,21,,False
11         Igor,24,4.5,False
12     Sthefanie,26,9.5,True
13         Mirla,25,9.0,True
14           Paulo,37,,False
15        Mylena,29,7.0,True
16           Lucas,33,,False
17         Nadia,34,8.0,True

In [7]:
type(dados_alunos)

pandas.DataFrame

In [ ]:
dados_alunos.head()

  Nome,Idade,Notas,Aprovado
0           Ary,20,7.5,True
1             Ana,18,,False
2        Cátia,27,2.5,False
3        Denis,18,5.0,False
4         Beto,21,10.0,True

In [13]:
dados_alunos.tail()

   Nome,Idade,Notas,Aprovado
13         Mirla,25,9.0,True
14           Paulo,37,,False
15        Mylena,29,7.0,True
16           Lucas,33,,False
17         Nadia,34,8.0,True

In [14]:
dados_alunos.shape

(18, 1)

In [ ]:
dados_alunos.describe()

<bound method NDFrame.describe of    Nome,Idade,Notas,Aprovado
0            Ary,20,7.5,True
1              Ana,18,,False
2         Cátia,27,2.5,False
3         Denis,18,5.0,False
4          Beto,21,10.0,True
5            Bruna,23,,False
6           Dara,21,7.0,True
7         Carlos,19,6.0,True
8         Alice,35,5.6,False
9            Vitor,28,,False
10          Daniel,21,,False
11         Igor,24,4.5,False
12     Sthefanie,26,9.5,True
13         Mirla,25,9.0,True
14           Paulo,37,,False
15        Mylena,29,7.0,True
16           Lucas,33,,False
17         Nadia,34,8.0,True>

In [17]:
estatisticas = dados_alunos.describe()
estatisticas

       Nome,Idade,Notas,Aprovado
count                         18
unique                        18
top              Ary,20,7.5,True
freq                           1

In [ ]:
dados_alunos